<Project>
  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <LithoSharpMarkdownComponentVersion>2.0.0-preview.2</LithoSharpMarkdownComponentVersion>
    <LithoSharpMarkdownSourceVersion Condition="'$(LithoSharpMarkdownSourceVersion)' == ''">$(LithoSharpMarkdownComponentVersion)</LithoSharpMarkdownSourceVersion>
    <RepositoryUrl>https://github.com/Htkym/lithosharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/Htkym/lithosharp</PackageProjectUrl>
  </PropertyGroup>
</Project>
