<Project>
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="LithoSharpCollection" />
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="LithoSharpId" />
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="LithoSharpRoute" />
    <CompilerVisibleProperty Include="MSBuildProjectDirectory" />
  </ItemGroup>
</Project>
