"""Generate the pinned WHATWG character table and independent test expectations.

Download the two URLs in character-reference-provenance.json manually, then:
python eng/html/GenerateCharacterReferences.py <entities.json> <WHATWG LICENSE>
No network request, build, package generation, or publication is performed here.
"""
import hashlib
import json
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parents[2]
entities_bytes = pathlib.Path(sys.argv[1]).read_bytes()
license_bytes = pathlib.Path(sys.argv[2]).read_bytes()
entity_sha = "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6"
license_sha = "85dc6f5ccb57a6fe8c33d158f9fc8fc7ee5655a5d3db2cdd131c6a3d0f48a864"
if hashlib.sha256(entities_bytes).hexdigest() != entity_sha:
    raise ValueError("entities.json SHA256 does not match the pinned source")
if hashlib.sha256(license_bytes).hexdigest() != license_sha:
    raise ValueError("WHATWG LICENSE SHA256 does not match the pinned license")
entries = json.loads(entities_bytes)
if len(entries) != 2231:
    raise ValueError("Expected exactly 2231 named character references")
for name, item in entries.items():
    if not name.startswith("&") or "\n" in name or "=" in name:
        raise ValueError(f"Invalid named character reference: {name!r}")
    if "".join(chr(point) for point in item["codepoints"]) != item["characters"]:
        raise ValueError(f"Code points and characters disagree for {name!r}")

rows = [name[1:] + "=" + ",".join(format(cp, "X") for cp in item["codepoints"])
        for name, item in sorted(entries.items())]
table = """// Generated by eng/html/GenerateCharacterReferences.py. Do not edit by hand.
// Copyright © WHATWG (Apple, Google, Mozilla, Microsoft).
// Incorporated source-code portions: BSD-3-Clause; see licenses/WHATWG.HTML.LICENSE.txt.
namespace LithoSharp.HtmlParsing;

internal static partial class HtmlCharacterReferences
{
    private const int LongestName = %d;
    private const string EncodedEntries = \"\"\"
%s
        \"\"\";
}
""" % (max(len(name) - 1 for name in entries), "\n".join("        " + row for row in rows))
(root / "src/LithoSharp/HtmlParsing/HtmlCharacterReferences.g.cs").write_text(table, encoding="utf-8", newline="\n")
fixtures = root / "tests/LithoSharp.Tests/Fixtures/HtmlTokenization"
fixtures.mkdir(parents=True, exist_ok=True)
(fixtures / "named-character-references.json").write_text(
    json.dumps({name: item["characters"] for name, item in sorted(entries.items())},
               ensure_ascii=True, indent=2) + "\n", encoding="utf-8", newline="\n")
(root / "licenses/WHATWG.HTML.LICENSE.txt").write_bytes(license_bytes)
provenance = {
    "source": "https://html.spec.whatwg.org/entities.json",
    "sourceSha256": entity_sha,
    "sourceBytes": len(entities_bytes),
    "entries": len(entries),
    "retrievedDate": "2026-10-09",
    "license": "https://raw.githubusercontent.com/whatwg/html/main/LICENSE",
    "licenseSha256": license_sha,
    "sourceCodeLicense": "BSD-3-Clause",
    "upstreamCopyright": "WHATWG (Apple, Google, Mozilla, Microsoft)",
    "transformation": "Drop leading ampersand; ASCII-sort names; encode code points as hexadecimal. No entries omitted.",
    "generatedSource": "src/LithoSharp/HtmlParsing/HtmlCharacterReferences.g.cs",
    "testExpectations": "tests/LithoSharp.Tests/Fixtures/HtmlTokenization/named-character-references.json"
}
(root / "eng/html/character-reference-provenance.json").write_text(
    json.dumps(provenance, indent=2) + "\n", encoding="utf-8", newline="\n")
