<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <PackageId>LithoSharp.ProjectTemplates</PackageId>
    <Authors>Htkym</Authors>
    <Description>Docs, Blog, custom C#, and MDX/React site templates for LithoSharp.</Description>
    <RepositoryUrl>https://github.com/Htkym/lithosharp</RepositoryUrl>
    <Version>0.3.1</Version>
    <PackageType>Template</PackageType>
    <PackageTags>dotnet-new;templates;static-site;LithoSharp</PackageTags>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="README.md" />
    <None Include="content\**\*" Exclude="content\**\bin\**;content\**\obj\**;content\**\dist\**;content\**\packages.lock.json" Pack="true" PackagePath="content\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup><None Include="../../src/LithoSharp/icon.png" Pack="true" PackagePath="/" /></ItemGroup>
</Project>
