using System.Collections.Concurrent;
using System.Collections.Immutable;
using System.IO.Compression;
using System.Reflection;
using System.Runtime.Loader;
using System.Runtime.Versioning;
using System.Security.Cryptography;
using System.Text.Json;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace LithoSharp.Analyzers.Tests;

[NotInParallel]
public sealed partial class AnalyzerPackageHostTests
{

    [Test]
    public async Task PackedAnalyzerLoadsAtRoslyn414AndReportsOneOriginalSpanCanary()
    {
        var package = Packed.Value;
        var loaded = new ConcurrentBag<string>();
        AssemblyLoadEventHandler handler = (_, e) => loaded.Add(e.LoadedAssembly.GetName().Name!);
        AppDomain.CurrentDomain.AssemblyLoad += handler;
        try
        {
            Check(typeof(CSharpCompilation).Assembly.GetName().Version == new Version(4, 14, 0, 0), "Actual Roslyn host must be4.14");
            Check(package.Assembly.GetCustomAttribute<TargetFrameworkAttribute>()?.FrameworkName == ".NETStandard,Version=v2.0", "Actual analyzer must be netstandard2.0");
            Check(package.Assembly.GetReferencedAssemblies().All(a => !Forbidden(a.Name!)), "Analyzer runtime dependency boundary");
            const string source = "// 😀 original UTF16 evidence\nclass C { void M() { var x = LithoSharp.SiteUrl.FromAbsolute(\"file:///tmp/private\"); } }";
            var compilation = Compile(source, core: true);
            Check(!compilation.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error), "Canary compilation must bind the real Core metadata");
            var diagnostics = await Analyze(compilation);
            Check(diagnostics.Length == 1 && diagnostics[0].Id == "LSA1001" && diagnostics[0].Severity == DiagnosticSeverity.Error, "Actual package analyzer must execute and emit exactly one canary");
            var expected = new TextSpan(source.IndexOf("\"file:///tmp/private\"", StringComparison.Ordinal), "\"file:///tmp/private\"".Length);
            Check(diagnostics[0].Location.SourceSpan == expected && diagnostics[0].Location.SourceTree?.FilePath == "canary.cs", "Original argument UTF16 span");
            var allLoaded = AppDomain.CurrentDomain.GetAssemblies().Select(a => a.GetName().Name!).ToArray();
            Check(!allLoaded.Any(Forbidden), "Core/Markdown/Node/MSBuild/Skia must not be loaded into the host");
            var evidence = new { task = "RA-01", package.Path, package.Version, package.Sha256,
                analyzerAssemblySha256 = Sha(File.ReadAllBytes(package.Assembly.Location)),
                targetFramework = package.Assembly.GetCustomAttribute<TargetFrameworkAttribute>()!.FrameworkName,
                actualRoslyn = typeof(CSharpCompilation).Assembly.FullName,
                actualCommon = typeof(Compilation).Assembly.FullName,
                coreMetadataPath = Required("RA01_CORE_METADATA"), coreMetadataSha256 = Sha(File.ReadAllBytes(Required("RA01_CORE_METADATA"))),
                diagnostic = new { diagnostics[0].Id, severity = diagnostics[0].Severity.ToString(), start = expected.Start, length = expected.Length },
                loadedDuringCanary = loaded.Distinct().Order().ToArray(), forbiddenLoaded = allLoaded.Where(Forbidden).ToArray(),
                analyzerReferences = package.Assembly.GetReferencedAssemblies().Select(a => a.FullName).ToArray(),
                selectedSourceMode = "fixed-preview.3", hostRuntime = System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription };
            File.WriteAllText(Required("RA01_HOST_PROOF"), JsonSerializer.Serialize(evidence, new JsonSerializerOptions { WriteIndented = true }));
        }
        finally { AppDomain.CurrentDomain.AssemblyLoad -= handler; }
    }

    [Test]
    public async Task NoCoreAndLookalikeUserSymbolsStayOutsideTheAnalyzerScope()
    {
        Check((await Analyze(Compile("class C {}", core: false))).Length == 0, "Core-free fast path");
        const string lookalike = "namespace LithoSharp { public sealed class SiteUrl { public static SiteUrl FromAbsolute(string value) => new SiteUrl(); } } class C { void M() { LithoSharp.SiteUrl.FromAbsolute(\"file:///tmp/private\"); } }";
        Check((await Analyze(Compile(lookalike, core: false))).Length == 0, "User namespace/name match is not the Core assembly symbol");
    }

    [Test]
    public async Task UnknownValidAndOutOfScopeUrlsDoNotBecomeInvalidValues()
    {
        const string source = "class C { void M(string unknown) { LithoSharp.SiteUrl.FromAbsolute(unknown); LithoSharp.SiteUrl.FromAbsolute(\"https://example.com\"); } }";
        Check((await Analyze(Compile(source, core: true))).Length == 0, "Unknown stays unknown; valid URL follows the shared runtime guard");
        const string generated = "// <auto-generated/>\nclass C { void M() { LithoSharp.SiteUrl.FromAbsolute(\"file:///tmp/private\"); } }";
        Check((await Analyze(Compile(generated, core: true, file: "generated.g.cs"))).Length == 0, "Generated-code policy");
    }

    [Test]
    public async Task CancelledCompilerAnalysisDoesNotReturnAResult()
    {
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();
        var cancelled = false;
        try { await Analyze(Compile("class C {}", core: false), cancellation.Token); }
        catch (OperationCanceledException) { cancelled = true; }
        Check(cancelled, "Cancelled packed analyzer pipeline must not produce a result");
    }

}
